# Site
name: 'cfrenzel'
description: 'blog of cfrenzel'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'cfrenzel'
email: 'cfrenzel@gmail.com'
mailchimp-list: ''
highlighter: rouge

include: ["_pages"]
permalink: /:title/

# Collections
collections_dir: collections
collections:
  - reading_list

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  #- jekyll/tagging
  
authors:
    camron:
      name:           Camron Frenzel
      site:           https://cfrenzel.github.io
      avatar:         assets/images/avatar-cam.jpg
      email:          cfrenzel@gmail.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: camron
      avatar: assets/images/avatar-cam.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Tagging (/_pluging tags.rb/site.rb )
tag_page_layout: tag-page
tag_page_dir: tags


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]