version: '{build}'
image: Ubuntu
access_token:
    secure: XnBi8Mi7PoisgrK4u76B1JxFeZlCgS9VeKWeVnJHrzFqXzfXGhtHexcLYYIfF4eL
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
test: off
deploy_script:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "cfrenzel@gmail.com"
  - git config --global user.name "cfrenzel"
  - git subtree push --prefix=_site https://github.com/cfrenzel/cfrenzel.github.io.git master